import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { chromium } from "playwright";
import { createBranch } from "../dist/index.js";
import { startServer } from "../dist/server.js";
import { achievementsView } from "../dist/delight.js";
import { signIn, openPlace } from "./new-window-places.mjs";
import { emptyNight } from "../dist/seasons/rings-store.js";
import { discardTemp } from "./temp-dir.mjs";

test("Library reviews pending facts, rejects individually, and accepted preference is recalled after engine restart", async (t) => {
  const temp = process.platform === "win32" ? "C:/Users/bishi/AppData/Local/Temp/Codex-session-files" : tmpdir();
  await mkdir(temp, { recursive: true });
  const root = await mkdtemp(join(temp, "branch-memory-review-"));
  const provider = { name: "recall", async complete(request) {
    const reply = request.messages.findLast((m) => m.role === "tool");
    if (reply) {
      const result = JSON.parse(reply.content).result;
      return { content: result.map((m) => m.data.text).join("; "), toolCalls: [] };
    }
    return { content: "", toolCalls: [{ id: "recall", name: "memory.search", arguments: '{"query":"cedar"}' }] };
  } };
  const options = { workspace: join(root, "workspace"), dataDir: join(root, "data"), provider };
  let app = await createBranch(options);
  let server = await startServer(app, { dataDir: options.dataDir, port: 0 });
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await server.close(); await app.close(); await discardTemp(root); });
  const page = await browser.newPage();
  const errors = [];
  page.on("pageerror", (e) => errors.push(e.message));
  app.store.review.configure("local", { review: false, requireApproval: true });
  const saved = await app.runtime.executeTool("memory.put", { text: "I prefer cedar notebooks", source: "Owner preference", kind: "preference", project: "default" });
  assert.equal(saved.staged, true);
  const rejected = app.store.review.propose("local", { kind: "put", text: "I prefer pine notebooks", source: "Other suggestion" });
  assert.equal(app.store.list("memory", "local").length, 0, "proposal is not a durable memory");
  const before = achievementsView(app.store, "local");
  assert.equal(before.list.find((item) => item.id === "records:memory:1").got, undefined, "no saved-memory award while pending");
  await fetch(new URL("/api/onboarding", server.url), { method: "POST", headers: { authorization: `Bearer ${server.token}`, "content-type": "application/json" }, body: '{"done":true}' });
  await signIn(page, server);
  await openPlace(page, "library", "memory");
  const acceptRow = page.locator(`[data-memory-proposal="${saved.proposalId}"]`);
  await acceptRow.getByRole("button", { name: "Accept", exact: true }).click();
  await acceptRow.waitFor({ state: "detached" });
  const rejectRow = page.locator(`[data-memory-proposal="${rejected.id}"]`);
  await rejectRow.getByRole("button", { name: "Reject", exact: true }).click();
  await rejectRow.waitFor({ state: "detached" });
  assert.equal(app.store.list("memory", "local").length, 1);
  assert.ok(achievementsView(app.store, "local").list.find((item) => item.id === "records:memory:1").got, "award after durable acceptance");
  assert.equal(app.store.review.proposals("local", "all").find((p) => p.id === rejected.id).status, "rejected");
  await server.close();
  await app.close();
  app = await createBranch(options);
  server = await startServer(app, { dataDir: options.dataDir, port: 0 });
  const recalled = await app.runtime.run({ prompt: "Which notebooks do I prefer?", permissions: ["memory.read"] });
  assert.equal(recalled.status, "completed");
  assert.match(recalled.output, /cedar notebooks/);
  assert.doesNotMatch(recalled.output, /pine/);
  const document = "---\nname: cedar-ordering\ndescription: Use when ordering cedar notebooks\n---\nOrder the right notebooks.";
  const skill = app.store.skills.install("local", { document });
  const seed = app.gardener.plantBud({ evidence: "Built notebook ordering", tasks: [], sourceRunIds: [] });
  app.gardener.book.saveSeed({ ...seed, name: skill.name, skillId: skill.id, document, status: "adopted" });
  const proof = { tasks: 3, without: { mean: 0.4, scores: [0.4], errors: 0, tokens: 20 }, with: { mean: 0.8, scores: [0.8], errors: 0, tokens: 15 }, gain: 0.4, unreadable: null, model: "stand-in", ranAt: new Date().toISOString() };
  app.gardener.book.write({ action: "adopted", seedId: seed.id, name: skill.name, reason: "proved", proof, before: [{ skillId: skill.id, activeVersion: null }], after: [{ skillId: skill.id, activeVersion: skill.activeVersion }] });
  app.rings.book.saveNight({ id: "night-fixture", scope: "local", night: "2026-09-27", status: "done", startedAt: new Date().toISOString(), finishedAt: new Date().toISOString(), model: "stand-in", modelKind: "local", data: emptyNight(), seenAt: null });
  await page.goto(server.url);
  await page.evaluate(() => localStorage.clear());
  await signIn(page, server);
  await openPlace(page, "library", "seasons");
  await page.getByText("Matching tasks: 3 · Before 40% · After 80% · Gain 40.0 points", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Set aside", exact: true }).click();
  await page.getByRole("button", { name: "Restore", exact: true }).waitFor();
  assert.equal(app.store.skills.view("local", skill.id).activeVersion, null);
  await page.getByRole("button", { name: "Restore", exact: true }).click();
  await page.getByRole("button", { name: "Set aside", exact: true }).waitFor();
  assert.ok(app.store.skills.view("local", skill.id).activeVersion);
  assert.deepEqual(errors, []);
});
